### PR TITLE
chore: tweak dark mode backgrounds

### PR DESCRIPTION
**Pull request by dummdidumm**
- make the darkest one a bit lighter (else it's just too dark)
- turn down background saturation to give the whole thing a bit of a warmer feeling (the blue makes it overly cold)
- remove blue from text, makes it brighter yet more pleasing to the eye

### CODE REVIEW

**Comment by Rich-Harris** [comment]
It doesn't feel warmer to me, just greyer. Admittedly it's hard to judge a dark theme when I'm near a window

**Comment by benmccann** [comment]
I actually turned off all my lights and drew my blinds while testing this 😆

**Comment by dummdidumm** [comment]
You're doing this wrong, people primarily use dark mode during the day, so it's a _feature_ of this whole thing being lighter.

> most sites are pretty dark in dark mode. e.g. I just checked https://vite.dev/guide/ and the background is pretty dark there

This PR has a _darker_ background that your example. Just proves my point that the current dark is too dark/cold. We can make the light text a notch lighter if that's what you're saying.

**Comment by Rich-Harris** [comment]
> Blue == cold, less blue == warmer

In the colour theory sense, yes. I'm talking about how it _feels_. We associate bright blue skies with warmth, for example! In this case the deep blue feels to me like a luxurious velvet robe whereas the grey feels impersonal and sci-fi-ish. I don't actually think either is quite right — I can't tell if it needs to be something in between or something off to one side.

> people primarily use dark mode during the day

People baffle me.

> I just checked https://vite.dev/guide/ and the background is pretty dark

Worth noting that the situation is reversed over there — they have a darker sidebar and a lighter main content area, whereas we have the opposite.

**Comment by Rich-Harris** [comment]
300 is purple and looks absolutely mad:

image

The Svelte orange hue is 12, and with 10% saturation at various lightnesses it looks... not great honestly:

image

A bluish tint works partly because it's very common and feels night-time-ish, but partly because it _contrasts_ with the orange rather than using it.

Is there an issue where people have complained about the background colour? I remember when we first introduced it (replacing the greys we'd had prior to that point) and everyone on the team was like 'oh my god this looks so much better'. Again, not saying it's perfect now — it's definitely not — but this feels like a step back towards where we were prior to that.

**Comment by dummdidumm** [comment]
> Is there an issue where people have complained about the background colour?

I myself find the dark mode off-putting, it's straining on my eyes because the background is so dark, yet the text has this tint of blue and so even if it has high contrast on paper it still feels washed out.

Also these people: https://github.com/sveltejs/svelte.dev/issues/517#issuecomment-2442951290

This PR tries to find a sweet spot between having that aesthetic blue and making the background lighter to make it more pleasant on the eyes.

**Comment by benmccann** [comment]
Vite's main content is lighter, but the page is on average darker because their left nav is so much darker than ours. I just tried this PR with changing the nav to a much darker color and it looks much better to me. What do you think about trying that out?

**Comment by Rich-Harris** [comment]
merged #765, closing

**Pull request closed without merging**
