### PR TITLE
feat: add devtools updates

### PR DESCRIPTION
**Pull request by ignatiusmb**
Originally from https://github.com/sveltejs/svelte-devtools/pull/213
Prerequisite for https://github.com/sveltejs/svelte-devtools/issues/207

### CODE REVIEW

**Comment by dummdidumm** [comment]
Can you add a comment to the code explaining why we need this?

**Comment by ignatiusmb** [comment]
Added a comment on top of the file. I haven't really thought of other plans for `/devtools`, but I'd guess we'd want to compartmentalize this into its own route, instead of `https://svelte.dev/updates.json`.

**Comment by Rich-Harris** [comment]
What happens if we're rate-limited (or the request fails for some other reason) as we're trying to prerender?

Note also that this _won't_ update when the tags update, only when the tags update _and_ we've redeployed the site, which depending on what other activity is happening could be a long delay.

We could try making it an ISR route? Otherwise I think it has to live elsewhere

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
Converted it to an ISR route, checked and it works perfectly! It will revalidate every 5 minutes, so we should stay comfortably under rate limits.

**Pull request merged**
