### PR TITLE
Add 'docs:' search filter

### PR DESCRIPTION
**Pull request by PixelSoftwareStudios**
**What:** 
 A way to only search documentation results in the global search bar.
 
**Why:** 
Satisfies Issue #661

**How:** 
To test, open the search bar from anywhere, type in a phrase like "welcome" which will show both Docs and Tutorials results, then type "docs:welcome" and it will only show documentation results with that phrase.

### CODE REVIEW

**Comment by benmccann** [comment]
I agree the search is quite problematic, but this doesn't feel like the right solution to me. E.g. I'm frequently frustrated when searching for svelte docs and getting sveltekit docs. This wouldn't help at all with that.

**Comment by Rich-Harris** [comment]
Agree, I'm afraid this doesn't scale — 'docs' isn't the operator, it's the _operand_. Something like this would make more sense:

- `state in:tutorial`
- `styles in:docs/svelte`
- `load in:docs/kit`

Needs to be paired with a discovery mechanism of course. Bonus points if we can offer dropdown autocompletes when you start typing `in:`.

**Comment by benmccann** [comment]
I think we should also play around with other solutions. It's been very common that I'm in the Svelte docs looking for something and none of the Svelte results show up because they're buried by SvelteKit results. I don't really want to have to do more typing to make them show up. 

I agree with the user in https://github.com/sveltejs/svelte.dev/issues/661#issuecomment-2440112495. I'm an advanced user, so I never want to see the tutorial results. I think there could be a toggle or tab setting or something that is saved across searches so that I don't have to append a filter to the end of every single search that I do and can just set it a single time and have it saved.

I'd really just like to see results for the docs that I'm in by default and then have the other results in another tab. It could potentially save which one is shown by default when you do a search then.

**Comment by Rich-Harris** [comment]
I'm a relatively advanced user myself and I refer back to the tutorial frequently. I think that prioritising the current section makes sense and is a quick win. I think an `in:` operator would also be useful though is less low-hanging fruit (mostly because of the discoverability requirement). I don't think we should make things convoluted with saved preferences and tabs and whatnot.

**Pull request closed without merging**
