### PR TITLE
add sync-docs README

### LINKED ISSUE #573: Remove `USE_GIT`
Why do we need it?

The way I had it setup originally was that if a directory was already present, it wouldn't try to clone the repo again. That would let you symlink in any repos that you wanted to

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #573

### CODE REVIEW

**Comment by benmccann** [comment]
do we no longer have to set `USE_GIT=true` when running it?

**Comment by Rich-Harris** [comment]
correct

**Comment by Rich-Harris** [comment]
(I mean, if you want to pull from GitHub then you should use the `-p` or `--pull` flag, but there's no more env var)

**Comment by benmccann** [comment]
Is there any reason we wouldn't make `--pull` the default? What does it do if you already have a repo and run it without any args?

**Comment by Rich-Harris** [comment]
It will sync from whatever state the repo is currently in. The assumption is that if you're interacting with this stuff manually, you're working with a symlinked repo and you're probably making edits in it. In that case, you definitely don't want to pull every time you sync

**Review by trueadm — APPROVED** [review]

**Pull request merged**
