### PR TITLE
shrink font size when georgia is used

### PR DESCRIPTION
**Pull request by Rich-Harris**
@dummdidumm how's this?

### CODE REVIEW

**Comment by dummdidumm** [comment]
yeah much better - should be done for the sans-serif font as-well.

**Comment by Rich-Harris** [comment]
Why? The reason to change the size of Georgia is that it has fatter glyphs than EB Garamond. If we change the size of the sans font on low res screens it'll just mess up the ratio of body copy font size to everything else.

Unless you're saying we should change the sans font size across the board? That seemed to be an unpopular opinion before

**Comment by dummdidumm** [comment]
This is how much I get to see on the old site, which was pleasant to read size-wise 
image

This is how much I get to see on the new site currently (using sans-serif, with serif it's the same)
image

It's just way too big

**Comment by dummdidumm** [comment]
Reducing line-height would also help, `line-height: 1.5` is good

**Comment by Rich-Harris** [comment]
Oh, interesting — didn't realise that we had 1.7 for low resolution screens — I assume the intent was to have 1.7 for Georgia and everything else, but you were seeing 1.7 on low res screens in sans mode.

Changed it to be 1.5 across the board, I think it looks fine. I nudged the sans font size down as well

**Pull request merged**
